[package]
name = "toy-farm-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
petgraph = "0.6"
anyhow = { workspace = true }
